version: 1

jobs:
  # General example
  hello:
    schedule: "* * * * *"
    command: "echo 'Hello from CronYAML'"
  hello_remote:
    schedule: "*/5 * * * *"
    source: "https://github.com/NaoCoding/cronyaml/blob/main/examples/remote/hello.js"
    args:
      - "Hello from the GitHub example script"
